/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvantagesRouteImport } from './routes/avantages'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProcessusRouteImport } from './routes/processus'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCostumesCeremoniesRouteImport } from './routes/services.costumes-ceremonies'
import { Route as ServicesCuirChaussuresRouteImport } from './routes/services.cuir-chaussures'
import { Route as ServicesLingeDeMaisonRouteImport } from './routes/services.linge-de-maison'
import { Route as ServicesPressingVetementsRouteImport } from './routes/services.pressing-vetements'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvantagesRoute = AvantagesRouteImport.update({
  id: '/avantages',
  path: '/avantages',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessusRoute = ProcessusRouteImport.update({
  id: '/processus',
  path: '/processus',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCostumesCeremoniesRoute =
  ServicesCostumesCeremoniesRouteImport.update({
    id: '/services/costumes-ceremonies',
    path: '/services/costumes-ceremonies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCuirChaussuresRoute = ServicesCuirChaussuresRouteImport.update({
  id: '/services/cuir-chaussures',
  path: '/services/cuir-chaussures',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLingeDeMaisonRoute = ServicesLingeDeMaisonRouteImport.update({
  id: '/services/linge-de-maison',
  path: '/services/linge-de-maison',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPressingVetementsRoute =
  ServicesPressingVetementsRouteImport.update({
    id: '/services/pressing-vetements',
    path: '/services/pressing-vetements',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avantages': typeof AvantagesRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/processus': typeof ProcessusRoute
  '/tarifs': typeof TarifsRoute
  '/services/costumes-ceremonies': typeof ServicesCostumesCeremoniesRoute
  '/services/cuir-chaussures': typeof ServicesCuirChaussuresRoute
  '/services/linge-de-maison': typeof ServicesLingeDeMaisonRoute
  '/services/pressing-vetements': typeof ServicesPressingVetementsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avantages': typeof AvantagesRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/processus': typeof ProcessusRoute
  '/tarifs': typeof TarifsRoute
  '/services/costumes-ceremonies': typeof ServicesCostumesCeremoniesRoute
  '/services/cuir-chaussures': typeof ServicesCuirChaussuresRoute
  '/services/linge-de-maison': typeof ServicesLingeDeMaisonRoute
  '/services/pressing-vetements': typeof ServicesPressingVetementsRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avantages': typeof AvantagesRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/processus': typeof ProcessusRoute
  '/tarifs': typeof TarifsRoute
  '/services/costumes-ceremonies': typeof ServicesCostumesCeremoniesRoute
  '/services/cuir-chaussures': typeof ServicesCuirChaussuresRoute
  '/services/linge-de-maison': typeof ServicesLingeDeMaisonRoute
  '/services/pressing-vetements': typeof ServicesPressingVetementsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avantages'
    | '/commander'
    | '/contact'
    | '/processus'
    | '/tarifs'
    | '/services/costumes-ceremonies'
    | '/services/cuir-chaussures'
    | '/services/linge-de-maison'
    | '/services/pressing-vetements'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avantages'
    | '/commander'
    | '/contact'
    | '/processus'
    | '/tarifs'
    | '/services/costumes-ceremonies'
    | '/services/cuir-chaussures'
    | '/services/linge-de-maison'
    | '/services/pressing-vetements'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/avantages'
    | '/commander'
    | '/contact'
    | '/processus'
    | '/tarifs'
    | '/services/costumes-ceremonies'
    | '/services/cuir-chaussures'
    | '/services/linge-de-maison'
    | '/services/pressing-vetements'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvantagesRoute: typeof AvantagesRoute
  CommanderRoute: typeof CommanderRoute
  ContactRoute: typeof ContactRoute
  ProcessusRoute: typeof ProcessusRoute
  TarifsRoute: typeof TarifsRoute
  ServicesCostumesCeremoniesRoute: typeof ServicesCostumesCeremoniesRoute
  ServicesCuirChaussuresRoute: typeof ServicesCuirChaussuresRoute
  ServicesLingeDeMaisonRoute: typeof ServicesLingeDeMaisonRoute
  ServicesPressingVetementsRoute: typeof ServicesPressingVetementsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avantages': {
      id: '/avantages'
      path: '/avantages'
      fullPath: '/avantages'
      preLoaderRoute: typeof AvantagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processus': {
      id: '/processus'
      path: '/processus'
      fullPath: '/processus'
      preLoaderRoute: typeof ProcessusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/costumes-ceremonies': {
      id: '/services/costumes-ceremonies'
      path: '/services/costumes-ceremonies'
      fullPath: '/services/costumes-ceremonies'
      preLoaderRoute: typeof ServicesCostumesCeremoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cuir-chaussures': {
      id: '/services/cuir-chaussures'
      path: '/services/cuir-chaussures'
      fullPath: '/services/cuir-chaussures'
      preLoaderRoute: typeof ServicesCuirChaussuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/linge-de-maison': {
      id: '/services/linge-de-maison'
      path: '/services/linge-de-maison'
      fullPath: '/services/linge-de-maison'
      preLoaderRoute: typeof ServicesLingeDeMaisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pressing-vetements': {
      id: '/services/pressing-vetements'
      path: '/services/pressing-vetements'
      fullPath: '/services/pressing-vetements'
      preLoaderRoute: typeof ServicesPressingVetementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvantagesRoute: AvantagesRoute,
  CommanderRoute: CommanderRoute,
  ContactRoute: ContactRoute,
  ProcessusRoute: ProcessusRoute,
  TarifsRoute: TarifsRoute,
  ServicesCostumesCeremoniesRoute: ServicesCostumesCeremoniesRoute,
  ServicesCuirChaussuresRoute: ServicesCuirChaussuresRoute,
  ServicesLingeDeMaisonRoute: ServicesLingeDeMaisonRoute,
  ServicesPressingVetementsRoute: ServicesPressingVetementsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
